# Configuration for pre-commit (https://pre-commit.com/), a tool to run
# formatters, linters, and other productivity tools before a commit.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: requirements-txt-fixer
      - id: check-yaml
        types: [file]
        files: ^tests/capi2_cores/.+\.core$
      - id: end-of-file-fixer
        # Test golden references
        exclude: ^tests/(.+\.(info|patch)|test_provider/.+\.v)
      - id: trailing-whitespace
        # Test golden references
        exclude: ^tests/(.+\.(info|patch)|test_provider/.+\.v)
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
      - id: pyupgrade
        # for now don't force to change from %-operator to {}
        args: [--keep-percent-format, --py3-plus]
  - repo: https://github.com/PyCQA/isort
    rev: "5.7.0"
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
